# Use root/example as user/password credentials
version: '3.8'

services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: intermedia_lms
    container_name: intermedia_lms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - intermedia_lms
  nginx:
    image: nginx:alpine
    container_name: intermedia_lms-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - intermedia_lms
networks:
  intermedia_lms:
    driver: bridge
